version: '3.7'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    network_mode: "host"
    environment:
      - TZ="US/Central"
    volumes:
      - /home/ben/Plex/config:/config
      - /home/ben/Plex/transcode:/transcode
      - /media/PlexMedia:/data

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - "9091:9091"
    volumes:
      - /media/PlexMedia:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=Netherlands
      - OPENVPN_USERNAME=overrideme
      - OPENVPN_PASSWORD=overrideme
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=overrideme
      - TRANSMISSION_RPC_PASSWORD=overrideme
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=1000
      - TRANSMISSION_WEB_UI=combustion
    logging:
      driver: "json-file"
      options:
        max-size: '10m'

  transmission-rss:
    container_name: transmission-rss
    image: nning2/transmission-rss
    restart: always
    volumes:
      - /media/DockerData/TransmissionRss/transmission-rss.conf:/etc/transmission-rss.conf

  nginx:
    container_name: nginx
    build: letsencrypt-reverse-proxy
    # This image isn't building for some reason. Use the repo
    #image: borigas/letsencrypt-reverse-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/ben/Certs:/etc/letsencrypt
      - /media/DockerData/Nginx/Sites:/etc/nginx/sites-available
    environment:
      - LETSENCRYPT_EMAIL="myemail@gmail.com"

  namecheap-dynamic-dns:
    container_name: ddns
    build: namecheap-dynamic-dns
    #image: borigas/namecheap-dynamic-dns
    restart: always
    environment:
      - DOMAIN_ARGS=@,domain1.org,[DDNS Password];@,domain2.com,[DDNS Password]
      
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock