version: '3.7'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: always
    network_mode: "host"
    environment:
      - TZ="US/Central"
    volumes:
      - /home/ben/Plex/config:/config
      - /home/ben/Plex/transcode:/transcode
      - /media/PlexMedia:/data

  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    ports:
      - "9091:9091"
    volumes:
      - /media/PlexMedia:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=netherlands
      - OPENVPN_USERNAME=overrideme
      - OPENVPN_PASSWORD=overrideme
      - WEBPROXY_ENABLED=false
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_USERNAME=overrideme
      - TRANSMISSION_RPC_PASSWORD=overrideme
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=1000
      - TRANSMISSION_WEB_UI=combustion
    logging:
      driver: "json-file"
      options:
        max-size: '10m'

  transmission-rss:
    container_name: transmission-rss
    image: nning2/transmission-rss
    restart: always
    volumes:
      - /media/DockerData/TransmissionRss/transmission-rss.conf:/etc/transmission-rss.conf

  nginx:
    container_name: nginx
    build: letsencrypt-reverse-proxy
    # This image isn't building for some reason. Use the repo
    #image: borigas/letsencrypt-reverse-proxy
    restart: always
    ports:
      - 10080:80
      - 10443:443
    volumes:
      - /home/ben/Certs:/etc/letsencrypt
      - /media/DockerData/Nginx/Sites:/etc/nginx/sites-available
    environment:
      - LETSENCRYPT_EMAIL="myemail@gmail.com"

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   restart: always
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp"
  #     - "80:80/tcp"
  #     - "443:443/tcp"
  #   environment:
  #     TZ: 'America/Chicago'
  #     # WEBPASSWORD: 'set a secure password here or it will be random'
  #   volumes:
  #     - '/media/DockerData/Pihole/pihole/:/etc/pihole/'
  #     - '/media/DockerData/Pihole/dnsmasq.d/:/etc/dnsmasq.d/'
  #   dns:
  #     - 127.0.0.1
  #     - 1.1.1.1

  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68/tcp"
      - "68:68/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "853:853/tcp"
      - "3000:3000/tcp"
    volumes:
      - '/media/DockerData/Adguard/work:/opt/adguardhome/work'
      - '/media/DockerData/Adguard/config:/opt/adguardhome/conf'
  
  cloudflare-dynamic-dns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns
    restart: always
    environment:
      - PROXIED=true
      
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      # Default interval of 5 min exhausts the pull rate limit (100 pulls / 6 hours) in 3 hours
      # Change to update at 10am UTC
      WATCHTOWER_SCHEDULE: 0 0 10 * * *
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock