version: '3.7'

services:
  plex:
  transmission:
    environment:
      - OPENVPN_USERNAME=[vpnuser]
      - OPENVPN_PASSWORD=[vpnpass]
      - TRANSMISSION_RPC_USERNAME=[web user name]
      - TRANSMISSION_RPC_PASSWORD=[web user password]
  nginx:
    environment:
      - LETSENCRYPT_EMAIL="[email@address.com]"
  cloudflare-dynamic-dns:
    environment:
      - API_KEY=[cloudflare api key]
      - ZONE=[domain.org]
  watchtower: