version: '3.7'

services:
  plex:
  transmission:
    environment:
      - OPENVPN_USERNAME=[vpnuser]
      - OPENVPN_PASSWORD=[vpnpass]
      - TRANSMISSION_RPC_USERNAME=[web user name]
      - TRANSMISSION_RPC_PASSWORD=[web user password]
  nginx:
    environment:
      - LETSENCRYPT_EMAIL="[email@address.com]"
  namecheap-dynamic-dns:
    environment:
      - DOMAIN_ARGS=@,[domain1.org],[domain1password];@,[domain2.com],[domain2password]
  watchtower: